{
  "hash": "8552225e04d9590a9ad5acd026acf346",
  "result": {
    "engine": "knitr",
    "markdown": "# Setting Up Your Environment\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n## Overview\n\nBefore you can write a Stan model, you need a working toolchain: a C++\ncompiler, CmdStan itself, and the R interface **cmdstanr**. This chapter\nwalks through every step, shows you how to verify that each piece is working,\nand ends with a complete first Stan program that you compile and run yourself.\n\nIf you hit a problem, the troubleshooting section at the end of this chapter\ncovers the most common installation failures by operating system.\n\n## Learning objectives\n\nBy the end of this chapter you will be able to:\n\n- Install CmdStan and cmdstanr on your machine and verify the toolchain.\n- Describe the structure of a `.stan` file (the six named blocks).\n- Compile and sample from a minimal Stan program using `cmdstanr`.\n- Read and interpret the summary output of a fitted Stan model.\n\n\n## The toolchain: what you are installing\n\nStan models are written in the Stan language, but they are **compiled to C++**\nbefore sampling. This means you need:\n\n1. **A C++ compiler**: the Stan compiler (`stanc`) translates `.stan` =>\n   `.cpp`; your system compiler then builds a fast binary.\n2. **CmdStan**: the command-line Stan interface; the actual sampler lives\n   here.\n3. **cmdstanr**: an R package that calls CmdStan from R, passes your data,\n   and returns results as tidy R objects.\n\n\n\n\n\n\n\n\n```{mermaid}\n%%| label: fig-toolchain\n%%| fig-cap: \"The Stan compilation and sampling toolchain.\"\n%%| fig-align: center\n\nflowchart TD\n    A(\"📄 Your .stan file\"):::user\n    B(\"🔧 stanc\\nStan → C++\"):::tool\n    C(\"📝 generated .cpp\"):::artifact\n    D(\"⚙️ C++ compiler\\ng++ / clang++\"):::tool\n    E(\"💾 compiled binary\\n.exe / .out\"):::artifact\n    F(\"📦 cmdstanr\\ncalls the binary,\\npasses your data\"):::tool\n    G(\"📊 posterior samples\\nin R\"):::result\n\n    A --> B --> C --> D --> E --> F --> G\n\n    classDef user     fill:#e8f4f2,stroke:#2e7d6a,color:#1a2e28\n    classDef tool     fill:#2e7d6a,stroke:#1a4a40,color:#ffffff\n    classDef artifact fill:#f0f5f4,stroke:#5c8a52,color:#1a2e28\n    classDef result   fill:#5c8a52,stroke:#3a6035,color:#ffffff\n```\n\n\n\n\n\n\n\n\n::: {.callout-note}\n**Why cmdstanr, not rstan?**  \nTwo R interfaces exist for Stan: `rstan` (the original) and `cmdstanr` (the\nnewer, recommended one). This handbook uses `cmdstanr` throughout because it tracks CmdStan releases closely, has a cleaner API, and avoids the compilation overhead that can make rstan slow to load. If you already use rstan, the Stan code in this handbook is identical, only the R calls differ.\n:::\n\n\n## Step 1: Install a C++ compiler\n\n### Windows\n\nInstall **Rtools** for your R version from\n<https://cran.r-project.org/bin/windows/Rtools/>. Accept all defaults.\nRtools provides the `g++` compiler that Stan needs.\n\nAfter installation, verify in R:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npkgbuild::has_build_tools(debug = TRUE)\n```\n:::\n\n\n\n\n\n\n\n\nYou should see `TRUE`. If not, restart R and try again.\n\n### macOS\n\nYou need the **Xcode Command Line Tools**, which provide the `clang++`\ncompiler:\n\n```bash\nxcode-select --install\n```\n\nA dialog will appear; click *Install*. After it completes, verify:\n\n```bash\nclang++ --version\n```\n\nIf you see a version string (e.g., `Apple clang version 15.0.0`), you are ready. On Apple Silicon (M1/M2/M3), this is sufficient and no additional steps are needed.\n\n### Linux\n\nMost Linux distributions ship with `g++`. Check:\n\n```bash\ng++ --version\n```\n\nIf the command is not found, install the build tools:\n\n```bash\n# Debian / Ubuntu\nsudo apt-get install build-essential\n\n# Fedora / RHEL\nsudo dnf groupinstall \"Development Tools\"\n```\n\n\n## Step 2: Install cmdstanr\n\n`cmdstanr` is not yet on CRAN; install it from the Stan R-universe:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(\n  \"cmdstanr\",\n  repos = c(\"https://stan-dev.r-universe.dev\", getOption(\"repos\"))\n)\n```\n:::\n\n\n\n\n\n\n\n\nLoad it and check that R can see it:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(cmdstanr)\ncmdstanr:::check_cmdstan_toolchain()\n```\n:::\n\n\n\n\n\n\n\n\nIf the toolchain check passes, you will see a message like:\n\n```\nThe C++ toolchain required for CmdStan is setup properly!\n```\n\nIf it fails, revisit Step 1 and consult the troubleshooting section below.\n\n\n## Step 3: Install CmdStan\n\nWith cmdstanr loaded, installing CmdStan is a single R call:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall_cmdstan(cores = 2)   # increase cores to speed up compilation\n```\n:::\n\n\n\n\n\n\n\n\nThis downloads and compiles CmdStan. It takes 5–15 minutes on the first\ninstall. You only need to do this once (and again when you want to upgrade).\n\n::: {.callout-tip}\n`install_cmdstan()` stores CmdStan in `~/.cmdstan/` by default. You can\ncheck and change this path with `cmdstan_path()` and the `CMDSTAN`\nenvironment variable in `.Renviron`.\n:::\n\nVerify the installation:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncmdstan_version()\n```\n:::\n\n\n\n\n\n\n\n\nYou should see something like `\"2.35.0\"`. Record this version — you will\nwant it for the methods section of any paper you write.\n\n\n## Step 4: Install companion R packages\n\nThe rest of the handbook uses these packages for working with and visualising\nStan output. Install them all now:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(c(\n  \"posterior\",   # working with posterior draws\n  \"bayesplot\",   # MCMC diagnostics and posterior plots\n  \"loo\",         # leave-one-out cross-validation\n  \"ggplot2\",     # all other plots\n  \"dplyr\",       # data wrangling\n  \"tidyr\",       # reshaping\n  \"patchwork\"    # combining plots\n))\n```\n:::\n\n\n\n\n\n\n\n\n\n## The anatomy of a Stan program {#sec-anatomy}\n\nEvery Stan program is divided into **named blocks**. Not all blocks are\nrequired, but they must appear in this fixed order when present:\n\n```stan\nfunctions {\n  // (optional) user-defined functions\n}\n\ndata {\n  // variables read from R\n}\n\ntransformed data {\n  // (optional) deterministic functions of the data\n}\n\nparameters {\n  // unknowns to be sampled\n}\n\ntransformed parameters {\n  // (optional) deterministic functions of parameters\n}\n\nmodel {\n  // priors and likelihood, the log posterior\n}\n\ngenerated quantities {\n  // (optional) predictions, log-likelihoods, derived quantities\n}\n```\n\nIn practice, you will use `data`, `parameters`, and `model` in nearly every\nprogram. The other blocks appear as models grow in complexity.\n\n@tbl-blocks summarises each block's role.\n\n| Block | Required | Purpose |\n|---|---|---|\n| `functions` | No | Define helper functions reused elsewhere |\n| `data` | Yes | Declare inputs passed from R |\n| `transformed data` | No | Pre-compute fixed quantities from data |\n| `parameters` | Yes | Declare the unknowns Stan samples |\n| `transformed parameters` | No | Derived quantities that are also saved |\n| `model` | Yes | Log-prior + log-likelihood contributions |\n| `generated quantities` | No | Posterior predictions, LOO log-likelihoods |\n\n: The seven named blocks of a Stan program. {#tbl-blocks}\n\n::: {.callout-warning}\n**Order matters.** Stan enforces that blocks appear in the order shown above.\nA common beginner mistake is writing `model` before `parameters`, in such case Stan will refuse to compile the program.\n:::\n\n\n## Your first Stan program\n\nLet us write, compile, and run a complete Stan program. The model is simple: we observe $N$ measurements drawn from a normal distribution, and we want to learn the mean $\\mu$ and standard deviation $\\sigma$.\n\n$$\ny_i \\sim \\text{Normal}(\\mu,\\, \\sigma), \\quad i = 1, \\ldots, N\n$$\n\n### Write the Stan file\n\nCreate a file called `normal_model.stan` in your working directory with the\nfollowing content. (In RStudio: *File => New File => Stan File*.)\n\n```stan\n// normal_model.stan\n// Estimate the mean and SD of a normal distribution.\n\ndata {\n  int<lower=1> N;      // number of observations; must be at least 1\n  vector[N] y;         // the observations\n}\n\nparameters {\n  real mu;             // population mean (unconstrained)\n  real<lower=0> sigma; // population SD (must be positive)\n}\n\nmodel {\n  // Priors\n  mu ~ normal(0, 10);      // weakly informative\n  sigma ~ exponential(1);     // puts mass on moderate values\n\n  // Likelihood\n  y ~ normal(mu, sigma);\n}\n\ngenerated quantities {\n  // Posterior predictive draw for one new observation\n  real y_rep = normal_rng(mu, sigma);\n}\n```\n\n### Compile the model\n\nIn R, point cmdstanr at the file:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(cmdstanr)\n\nmod <- cmdstan_model(\"normal_model.stan\")\n```\n:::\n\n\n\n\n\n\n\n\nCompilation happens once and is cached. You will see a progress message; when\nit finishes, `mod` is a `CmdStanModel` object.\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod   # print a summary\n```\n:::\n\n\n\n\n\n\n\n\n```\nCmdStanModel: normal_model\n  stan_file: normal_model.stan\n  exe_file:  normal_model\n  ...\n```\n\n### Prepare the data\n\nStan's `data` block expects an R list whose names exactly match the variable\nnames in the block:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\n\n# Simulate some data: true mu = 3, true sigma = 1.5\ny_obs <- rnorm(n = 50, mean = 3, sd = 1.5)\n\nstan_data <- list(\n  N = length(y_obs),\n  y = y_obs\n)\n```\n:::\n\n\n\n\n\n\n\n\n### Sample from the posterior\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit <- mod$sample(\n  data    = stan_data,\n  seed    = 2025,\n  chains  = 4,         # run 4 independent Markov chains\n  parallel_chains = 4, # use 4 CPU cores (adjust to your machine)\n  iter_warmup   = 1000,\n  iter_sampling = 1000,\n  refresh = 500        # print progress every 500 iterations\n)\n```\n:::\n\n\n\n\n\n\n\n\nYou will see output like:\n\n```\nRunning MCMC with 4 parallel chains...\nChain 1 Iteration:    1 / 2000 [  0%]  (Warmup)\nChain 1 Iteration:  500 / 2000 [ 25%]  (Warmup)\nChain 1 Iteration: 1000 / 2000 [ 50%]  (Warmup)\nChain 1 Iteration: 1001 / 2000 [ 50%]  (Sampling)\nChain 1 Iteration: 1500 / 2000 [ 75%]  (Sampling)\nChain 1 Iteration: 2000 / 2000 [100%]  (Sampling)\nChain 1 finished in 0.1 seconds.\n...\nAll 4 chains finished successfully.\nMean chain execution time: 0.1 seconds.\nTotal execution time: 0.2 seconds.\n```\n\n### Read the output\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit$summary()\n```\n:::\n\n\n\n\n\n\n\n\n```\n# A tibble: 3 × 10\n  variable  mean median    sd   mad    q5   q95  rhat ess_bulk ess_tail\n  <chr>    <dbl>  <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>    <dbl>    <dbl>\n1 lp__     -86.5  -86.2  1.01 0.726 -88.4 -85.5  1.00    1671.    2332.\n2 mu         3.06   3.06 0.214 0.212  2.71  3.41  1.00    3682.    2871.\n3 sigma      1.50   1.49 0.153 0.152  1.26  1.77  1.00    3745.    2901.\n```\n\nRead this table as follows:\n\n- **`mean` / `median`**: posterior mean and median for each parameter. Here\n  $\\hat{\\mu} \\approx 3.06$ and $\\hat{\\sigma} \\approx 1.50$ which are close to the true values of 3 and 1.5.\n- **`sd`**: posterior standard deviation (the Bayesian analogue of a standard error).\n- **`q5` / `q95`**: the 90% credible interval. We are 90% confident that\n  $\\mu$ lies between 2.71 and 3.41.\n- **`rhat`**: the $\\hat{R}$ convergence diagnostic. Values close to 1.00\n  (below 1.01) indicate that all chains agree, the sampler has converged.\n- **`ess_bulk` / `ess_tail`**: effective sample sizes. Values above ~400 are generally adequate; higher is better.\n\n::: {.callout-tip}\n**The `lp__` row** is the log posterior density evaluated at each draw. It is\ncomputed automatically and is useful for diagnosing problems, but you do not\ninterpret it as a parameter.\n:::\n\n\n## A first look at diagnostics\n\nEven at this early stage, it is good practice to look at the trace plots that shows the visual records of each chain's journey through parameter space:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(bayesplot)\n\nfit$draws() |>\n  mcmc_trace(pars = c(\"mu\", \"sigma\"))\n```\n:::\n\n\n\n\n\n\n\n\nWell-mixed chains look like \"fuzzy caterpillars\": each chain explores the\nsame region, with no trends, drift, or sticking (@fig-trace-example).\n\n\n\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Schematic trace plots. Left: problematic chains, one chain stuck at a different value (poor mixing).  Right: healthy chains, four chains overlapping, exploring the same region.\n](02-setup_files/figure-html/fig-trace-example-1.png){#fig-trace-example width=95%}\n:::\n:::\n\n\n\n\n\n\n\n\nWe will return to diagnostics in depth in @sec-anatomy and throughout Part V.\nFor now, if your trace plots look like the left panel and `rhat` is below\n1.01, your model has sampled successfully.\n\n\n## Saving and reloading a fit\n\nStan fits can take time. Save them so you do not need to refit:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit$save_object(\"normal_model_fit.rds\")\n\n# In a new R session:\nfit <- readRDS(\"normal_model_fit.rds\")\n```\n:::\n\n\n\n\n\n\n\n\n\n## Troubleshooting\n\n### \"C++ compiler not found\" (Windows)\n\nRtools is not on the PATH. Run this in R and then restart:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npkgbuild::find_rtools(debug = TRUE)\n```\n:::\n\n\n\n\n\n\n\n\nIf it cannot find Rtools, reinstall from\n<https://cran.r-project.org/bin/windows/Rtools/> and ensure *\"Add Rtools\nto system PATH\"* is checked.\n\n### \"Error: 'make' not found\" (macOS)\n\nThe Xcode Command Line Tools are missing or need updating:\n\n```bash\nxcode-select --install\n# or, if already installed but broken:\nsudo xcode-select --reset\n```\n\n### Compilation succeeds but sampling is very slow\n\nSet `parallel_chains` to the number of physical cores on your machine. Find\nthis in R with:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nparallel::detectCores(logical = FALSE)\n```\n:::\n\n\n\n\n\n\n\n\n### \"Initialization between (-2, 2) failed after 100 attempts\"\n\nStan initialises parameters randomly in the range (−2, 2) on the *unconstrained* scale. This error means the model's log posterior could not be evaluated at any of these starting points. This is usually a sign of a mis-specified model or data-block mismatch. Double-check that your `stan_data` list names exactly match the `data` block variable names, and that dimensions are correct.\n\n### `rhat` is above 1.01 or chains look like the right panel in @fig-trace-example\n\nConvergence failure. Common causes: too few warmup iterations, a poorly\nspecified model, or high posterior correlation between parameters. Try\n`iter_warmup = 2000` first. We discuss deeper fixes in @sec-debugging.\n\n\n## Summary\n\n- Stan requires a C++ compiler, CmdStan, and the cmdstanr R package.\n  Install them once with `install_cmdstan()` and they are ready for all\n  future work.\n- Every Stan program has up to seven named blocks in a fixed order:\n  `functions`, `data`, `transformed data`, `parameters`,\n  `transformed parameters`, `model`, `generated quantities`. The\n  three essential ones are `data`, `parameters`, and `model`.\n- The workflow is: write a `.stan` file → compile with `cmdstan_model()` →\n  pass data as a named R list → call `$sample()` → inspect with\n  `$summary()`.\n- Always check `rhat` (target: < 1.01) and trace plots before interpreting\n  results. A fuzzy-caterpillar trace is a healthy trace.\n\n\n## Exercises\n\n1. **Verify your installation.** Run the following and paste the output into\n   a text file to keep as a record of your environment:\n\n\n\n\n\n\n\n   ::: {.cell}\n   \n   ```{.r .cell-code}\n   cmdstan_version()\n   packageVersion(\"cmdstanr\")\n   packageVersion(\"posterior\")\n   R.version.string\n   ```\n   :::\n\n\n\n\n\n\n\n\n2. **Run the normal model.** Copy `normal_model.stan` from this chapter,\n   compile it, generate 100 observations from `rnorm(100, mean = 5, sd = 2)`,\n   and fit the model. Does `$summary()` recover the true parameters? What\n   happens to the width of the credible intervals if you reduce $N$ to 10?\n\n3. **Experiment with priors.** Change the prior on `mu` from\n   `normal(0, 10)` to `normal(0, 0.1)` (a very tight prior centred at zero)\n   and refit with the same data. How does the posterior for `mu` change?\n   What does this tell you about the influence of the prior relative to the\n   data?\n\n4. **Inspect the `generated quantities` block.** The model includes\n   `y_rep = normal_rng(mu, sigma)`. Extract this quantity with\n   `fit$draws(\"y_rep\")` and plot a histogram. What distribution does it\n   approximate, and why?\n\n\n## Further reading\n\n- cmdstanr documentation: <https://mc-stan.org/cmdstanr/>\n- Stan installation guide (all platforms):\n  <https://mc-stan.org/docs/cmdstan-guide/installation.html>\n- @stan2017 — the primary Stan reference; cite this in any publication\n  that uses Stan models.\n- @betancourt2017conceptual [§2] — brief, accessible description of HMC\n  warmup and why it matters for setting `iter_warmup`.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}